const productsData = [
  // Notebooks & Diaries
  {
    id: 1,
    name: "Classic Notebook",
    price: 199,
    category: "📓 Notebooks & Diaries",
    description: "Hardcover ruled notebook with 200 pages.",
    color: "Black",
    company: "Classmate",
    rating: 4.5,
    image: "notebook1.jpg",
  },
  {
    id: 2,
    name: "Pocket Diary",
    price: 99,
    category: "📓 Notebooks & Diaries",
    description: "Small diary with elastic closure, 100 pages.",
    color: "Brown",
    company: "Paperkraft",
    rating: 4.2,
    image: "diary1.jpg",
  },
  {
    id: 3,
    name: "Spiral Notebook",
    price: 149,
    category: "📓 Notebooks & Diaries",
    description: "Spiral-bound ruled notebook, 150 pages.",
    color: "Blue",
    company: "Navneet",
    rating: 4.3,
    image: "notebook2.jpg",
  },
  {
    id: 4,
    name: "Leather Journal",
    price: 399,
    category: "📓 Notebooks & Diaries",
    description: "Premium leather-bound journal with handmade paper.",
    color: "Dark Brown",
    company: "Luxor",
    rating: 4.8,
    image: "journal1.jpg",
  },
  {
    id: 5,
    name: "Executive Diary",
    price: 299,
    category: "📓 Notebooks & Diaries",
    description: "Luxury diary with premium pages and pen holder.",
    color: "Black",
    company: "Paperkraft",
    rating: 4.6,
    image: "diary2.jpg",
  },
  {
    id: 6,
    name: "Student Notebook Pack",
    price: 499,
    category: "📓 Notebooks & Diaries",
    description: "Set of 5 ruled notebooks for students.",
    color: "Assorted",
    company: "Classmate",
    rating: 4.7,
    image: "notebook3.jpg",
  },
  {
    id: 7,
    name: "Hardcover Sketchbook",
    price: 349,
    category: "📓 Notebooks & Diaries",
    description: "Hardbound sketchbook with thick drawing paper.",
    color: "White",
    company: "Camel",
    rating: 4.4,
    image: "sketchbook2.jpg",
  },
  {
    id: 8,
    name: "Mini Memo Pad",
    price: 79,
    category: "📓 Notebooks & Diaries",
    description: "Pocket-sized memo pad for quick notes.",
    color: "Yellow",
    company: "Post-it",
    rating: 4.3,
    image: "memopad1.jpg",
  },
  {
    id: 9,
    name: "Bullet Journal",
    price: 299,
    category: "📓 Notebooks & Diaries",
    description: "Dotted journal for bullet journaling.",
    color: "Grey",
    company: "Leuchtturm1917",
    rating: 4.8,
    image: "bulletjournal1.jpg",
  },

  // Art & Craft Supplies
  {
    id: 10,
    name: "Acrylic Paint Set",
    price: 599,
    category: "🎨 Art & Craft Supplies",
    description: "Set of 12 vibrant acrylic colors.",
    color: "Multicolor",
    company: "Faber-Castell",
    rating: 4.7,
    image: "paint1.jpg",
  },
  {
    id: 11,
    name: "Sketchbook A4",
    price: 249,
    category: "🎨 Art & Craft Supplies",
    description: "Thick, acid-free paper for sketching and drawing.",
    color: "White",
    company: "Camel",
    rating: 4.5,
    image: "sketchbook1.jpg",
  },
  {
    id: 12,
    name: "Watercolor Palette",
    price: 349,
    category: "🎨 Art & Craft Supplies",
    description: "24-color watercolor palette with brush.",
    color: "Multicolor",
    company: "Brustro",
    rating: 4.6,
    image: "watercolor1.jpg",
  },
  {
    id: 13,
    name: "Craft Paper Set",
    price: 199,
    category: "🎨 Art & Craft Supplies",
    description: "Assorted color craft papers for DIY projects.",
    color: "Multicolor",
    company: "Camel",
    rating: 4.4,
    image: "craftpaper1.jpg",
  },
  {
    id: 14,
    name: "Oil Pastels Set",
    price: 299,
    category: "🎨 Art & Craft Supplies",
    description: "Set of 24 smooth oil pastels.",
    color: "Multicolor",
    company: "Pentel",
    rating: 4.6,
    image: "oilpastels1.jpg",
  },
  {
    id: 15,
    name: "Paint Brushes (Set of 6)",
    price: 249,
    category: "🎨 Art & Craft Supplies",
    description: "Assorted paintbrush set for various strokes.",
    color: "Wooden",
    company: "Camel",
    rating: 4.5,
    image: "brushes1.jpg",
  },

  // School Stationery
  {
    id: 16,
    name: "Pencil Box",
    price: 150,
    category: "🏫 School Stationery",
    description: "Durable pencil box with multiple compartments.",
    color: "Blue",
    company: "Classmate",
    rating: 4.3,
    image: "pencilbox1.jpg",
  },
  {
    id: 17,
    name: "Exam Pads",
    price: 120,
    category: "🏫 School Stationery",
    description: "Sturdy writing pads for school and exams.",
    color: "Brown",
    company: "Camlin",
    rating: 4.2,
    image: "exampad1.jpg",
  },
  {
    id: 18,
    name: "Colored Pencils Set",
    price: 299,
    category: "🏫 School Stationery",
    description: "Set of 24 colored pencils for students.",
    color: "Multicolor",
    company: "Faber-Castell",
    rating: 4.6,
    image: "coloredpencils1.jpg",
  },

  // Office Supplies
  {
    id: 19,
    name: "Sticky Notes Cube",
    price: 199,
    category: "📎 Office Supplies",
    description: "400-page sticky notes cube.",
    color: "Yellow",
    company: "Post-it",
    rating: 4.5,
    image: "stickynotes2.jpg",
  },
  {
    id: 20,
    name: "Whiteboard Duster",
    price: 199,
    category: "📎 Office Supplies",
    description: "Magnetic duster for whiteboards.",
    color: "Black",
    company: "Kores",
    rating: 4.3,
    image: "duster1.jpg",
  },
  {
    id: 21,
    name: "Book Stand",
    price: 299,
    category: "📁 Files & Organizers",
    description: "Adjustable book stand for reading comfort.",
    color: "Black",
    company: "Cello",
    rating: 4.4,
    image: "bookstand1.jpg",
  },
  // Notebooks & Diaries
  {
    id: 22,
    name: "Traveler's Notebook",
    price: 349,
    category: "📓 Notebooks & Diaries",
    description: "Refillable leather travel journal with lined pages.",
    color: "Brown",
    company: "Moleskine",
    rating: 4.7,
    image: "travelnotebook1.jpg",
  },
  {
    id: 23,
    name: "Handmade Paper Journal",
    price: 399,
    category: "📓 Notebooks & Diaries",
    description: "Vintage-style journal with handmade paper.",
    color: "Tan",
    company: "Paperblanks",
    rating: 4.8,
    image: "handmadejournal1.jpg",
  },

  // Art & Craft Supplies
  {
    id: 24,
    name: "Charcoal Pencil Set",
    price: 249,
    category: "🎨 Art & Craft Supplies",
    description: "Set of 6 charcoal pencils for shading.",
    color: "Black",
    company: "Derwent",
    rating: 4.6,
    image: "charcoalpencil1.jpg",
  },
  {
    id: 25,
    name: "Canvas Board (Pack of 2)",
    price: 349,
    category: "🎨 Art & Craft Supplies",
    description: "Double-pack of A3 size canvas boards.",
    color: "White",
    company: "Camel",
    rating: 4.5,
    image: "canvasboard1.jpg",
  },
  {
    id: 26,
    name: "Fabric Paint Set",
    price: 399,
    category: "🎨 Art & Craft Supplies",
    description: "12-color fabric paint set for textiles.",
    color: "Multicolor",
    company: "Fevicryl",
    rating: 4.7,
    image: "fabricpaint1.jpg",
  },
  {
    id: 27,
    name: "Origami Paper Pack",
    price: 179,
    category: "🎨 Art & Craft Supplies",
    description: "100 sheets of assorted origami paper.",
    color: "Multicolor",
    company: "Faber-Castell",
    rating: 4.3,
    image: "origamipaper1.jpg",
  },

  // School Stationery
  {
    id: 28,
    name: "Gel Pens (Set of 10)",
    price: 199,
    category: "🏫 School Stationery",
    description: "Smooth-flow gel pens with assorted colors.",
    color: "Multicolor",
    company: "Reynolds",
    rating: 4.5,
    image: "gelpens1.jpg",
  },
  {
    id: 29,
    name: "Math Geometry Box",
    price: 249,
    category: "🏫 School Stationery",
    description: "Complete set of mathematical instruments.",
    color: "Silver",
    company: "Camlin",
    rating: 4.4,
    image: "geometrybox1.jpg",
  },
  {
    id: 30,
    name: "Ruler Set (Pack of 4)",
    price: 129,
    category: "🏫 School Stationery",
    description: "Set includes 15cm and 30cm rulers.",
    color: "Transparent",
    company: "Classmate",
    rating: 4.2,
    image: "rulerset1.jpg",
  },
  {
    id: 31,
    name: "Scientific Calculator",
    price: 999,
    category: "🏫 School Stationery",
    description: "Advanced scientific calculator for students.",
    color: "Black",
    company: "Casio",
    rating: 4.8,
    image: "calculator1.jpg",
  },

  // Office Supplies
  {
    id: 32,
    name: "Document Holder",
    price: 249,
    category: "📎 Office Supplies",
    description: "Portable document folder with multiple pockets.",
    color: "Black",
    company: "Solo",
    rating: 4.6,
    image: "documentholder1.jpg",
  },
  {
    id: 33,
    name: "Stapler with Pins",
    price: 199,
    category: "📎 Office Supplies",
    description: "Heavy-duty stapler with 500 free pins.",
    color: "Blue",
    company: "Kangaro",
    rating: 4.5,
    image: "stapler1.jpg",
  },
  {
    id: 34,
    name: "Paper Shredder",
    price: 2999,
    category: "📎 Office Supplies",
    description: "Cross-cut paper shredder for offices.",
    color: "Grey",
    company: "AmazonBasics",
    rating: 4.7,
    image: "shredder1.jpg",
  },
  {
    id: 35,
    name: "Desk Organizer",
    price: 399,
    category: "📎 Office Supplies",
    description: "Multi-compartment organizer for desk essentials.",
    color: "Black",
    company: "Cello",
    rating: 4.6,
    image: "deskorganizer1.jpg",
  },

  // Files & Organizers
  {
    id: 36,
    name: "Expanding File Folder",
    price: 349,
    category: "📁 Files & Organizers",
    description: "13-pocket expanding file for documents.",
    color: "Blue",
    company: "Solo",
    rating: 4.6,
    image: "expandingfile1.jpg",
  },
  {
    id: 37,
    name: "Clip File Folder",
    price: 199,
    category: "📁 Files & Organizers",
    description: "Durable clip file for office use.",
    color: "Black",
    company: "Solo",
    rating: 4.3,
    image: "clipfile1.jpg",
  },
  {
    id: 38,
    name: "Ring Binder A4",
    price: 299,
    category: "📁 Files & Organizers",
    description: "A4 size ring binder for documents.",
    color: "Red",
    company: "Cello",
    rating: 4.5,
    image: "ringbinder1.jpg",
  },
  {
    id: 39,
    name: "Drawer Storage Box",
    price: 799,
    category: "📁 Files & Organizers",
    description: "Plastic drawer box for storing files and papers.",
    color: "White",
    company: "Nilkamal",
    rating: 4.7,
    image: "storagebox1.jpg",
  },
  {
    id: 40,
    name: "Magazine Holder",
    price: 249,
    category: "📁 Files & Organizers",
    description: "Mesh magazine holder for easy access.",
    color: "Black",
    company: "Cello",
    rating: 4.4,
    image: "magazineholder1.jpg",
  },
  {
    id: 41,
    name: "Laminating Machine",
    price: 2499,
    category: "📁 Files & Organizers",
    description: "Compact laminator for documents and ID cards.",
    color: "Grey",
    company: "AmazonBasics",
    rating: 4.8,
    image: "laminator1.jpg",
  },
  {
    id: 42,
    name: "Index Cards (Pack of 100)",
    price: 199,
    category: "📁 Files & Organizers",
    description: "Set of 100 index cards for notes and references.",
    color: "White",
    company: "Solo",
    rating: 4.2,
    image: "indexcards1.jpg",
  },
];

export default productsData;
